name: Matrix Configuration

on: 
    push:
    workflow_dispatch: 

jobs: 
    deploy:
        strategy:
            fail-fast: false
            
            matrix:
                os: [ubuntu-latest, windows-latest, ubuntu-20.04]
                images: [hello-world, alpine]
                include: 
                    - os: ubuntu-20.04
                      images: amd64/alpine
                exclude:
                  - os: windows-latest
                    images: alpine
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo Docker Details
          run: docker info
        
        - name: Run Image on ${{ matrix.images }}
          run: docker run ${{ matrix.images }}

